/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.clientdetailsui;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Suvetha Kannan
 */

public class ClientFileChooser extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static String getUser;
    static String fName;
    Image img;
    public ClientFileChooser() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**public void paint(Graphics g)
    {
        // Draws the img to the BackgroundPanel.
        g.drawImage(img, 0, 0, null);
    }
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel(getUser);
        filesUploaded = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uploaded File Chooser");

        jLabel1.setText("Username");

        userName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userNameComponentShown(evt);
            }
        });

        filesUploaded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filesUploadedMouseClicked(evt);
            }
        });
        filesUploaded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filesUploadedActionPerformed(evt);
            }
        });
        filesUploaded.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                filesUploadedFocusGained(evt);
            }
        });
        filesUploaded.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filesUploadedKeyPressed(evt);
            }
        });

        jLabel3.setText("Files Uploaded");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filesUploaded, 0, 121, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filesUploaded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userNameComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameComponentShown

    private void filesUploadedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filesUploadedActionPerformed
            
            
    }//GEN-LAST:event_filesUploadedActionPerformed

    private void filesUploadedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filesUploadedKeyPressed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_filesUploadedKeyPressed

    private void filesUploadedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filesUploadedMouseClicked
        // TODO add your handling code here:
            
           Object contents = filesUploaded.getSelectedItem();
           System.out.println(contents);
           ClientLoader.displayFileName(contents);
           dispose();
            
    }//GEN-LAST:event_filesUploadedMouseClicked

    private void filesUploadedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filesUploadedFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_filesUploadedFocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String user) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
                
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               
                getUser = user;
                new ClientFileChooser().setVisible(true);
               
                DBConnection db = new DBConnection();
                Statement stmt = db.connect();
                try {
                ResultSet rs = stmt.executeQuery("select * from fileowner where owner= "
                    + "'" + getUser + "' ");
                while (rs.next()) {
                String groupName = rs.getString("fileName"); 
                // add group names to the array list
                 filesUploaded.addItem(groupName);
                } 

                rs.close(); 
            }
            catch (SQLException ex) {
            Logger.getLogger(ClientLoader.class.getName()).log(Level.SEVERE, null, ex);
            }

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox filesUploaded;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
